=== MichaelOdumosu57/XML_folder/XSLT_folder/XSLT_example/employee.dtd
<!ELEMENT class (employee,employee,employee)>
<!ELEMENT employee (firstname,lastname,nickname,salary)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT employee (firstname,lastname,nickname,salary)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT salary (#PCDATA)>
<!ELEMENT employee (firstname,lastname,nickname,salary)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT nickname (#PCDATA)>
<!ELEMENT salary (#PCDATA)>

=== MichaelOdumosu57/XML_folder/XSLT_folder/XSLT_example/employee.xml
<?xml version = "1.0"?>
<?xml-stylesheet type = "text/xsl" href = "employee.xsl"?>
<!DOCTYPE employee SYSTEM "employee.dtd">
<employee>
   <class id = "001">
      <firstname>Aryan</firstname>
      <lastname>Gupta</lastname>
      <nickname>Raju</nickname>
      <salary>30000</salary>
   </class>
   <class id = "024">
      <firstname>Sara</firstname>
      <lastname>Khan</lastname>
      <nickname>Zoya</nickname>
      <salary>25000</salary>
   </class>
   <class id = "056">
      <firstname>Peter</firstname>
      <lastname>Symon</lastname>
      <nickname>John</nickname>
      <salary>10000</salary>
   </class>
</employee>
